### ISSUE TITLE
about the structure of run_scripts

### ISSUE THREAD

**Issue by TyrionBian** [nlapier2/metalign_paper_replication#1]
Thanks for your excellent job. But I'm a little confuse about this place in run_scripts like  /tara_run_scripts. I just don't know the order and relationship of these scripts here. And also how to get the data you use.

**Comment by nlapier2** [comment]
Hi there,

Additional file 1 (e.g. the supplementary information) of our paper here (https://doi.org/10.1186/s13059-020-02159-0) has details about how these were run. Have you seen that? I just noticed that the repo's README still had the bioRxiv link, so I have updated that.

Best,
Nathan

**Comment by TyrionBian** [comment]
Thank you very much. I found it.
